version: '3'
services:
  mysql:
    build: ./mysql
    container_name: mysql57
    ports:
      - 43306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
